version: "3"

services:
  micro-weather-postgres:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=micro_weather_dev
      - POSTGRES_USER=micro_weather_dev
      - POSTGRES_PASSWORD=micro_weather_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data: